apiVersion: apps/v1
kind: Deployment
metadata:
  name: demucs-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demucs-worker
  template:
    metadata:
      labels:
        app: demucs-worker
    spec:
      containers:
      - name: demucs-worker
        image: bhuv005/demucs-worker:latest
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: "redis-master"
        - name: REDIS_MASTER_SERVICE_PORT
          value: "6379"
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "rootuser"
        - name: MINIO_SECRET_KEY
          value: "rootpass123"