# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir Flask jsonpickle pillow redis numpy minio flask-cors

# Make port 5000 available to the world outside this container
EXPOSE 9999

# Define environment variable
ENV FLASK_APP=rest-server.py

# Run app.py when the container launches
CMD ["python", "rest-server.py"]
